### ISSUE TITLE
Multiplayer / Dedicated server error : event registration error

### ISSUE THREAD

**Issue by aoakeley** [raiguard/Factorio-LtnManager#19]
Can not join server, player disconnects with following error ( [full log](https://gist.github.com/aoakeley/e96b199814c6c80f1ed20622f7e65524) ): 

`  34.155 Checksum for script __LogisticTrainNetwork__/control.lua: 2308678286  

  34.162 Checksum for script __LtnManager__/control.lua: 1048496621  
  34.166 Checksum for script __LTN_Combinator__/control.lua: 2315148836  
  34.167 Checksum for script __LTN_Content_Reader__/control.lua: 3089594493  
  38.760 Error ClientMultiplayerManager.cpp:1106: mod-LtnManager was not registered for the following events when the map was saved but has registered them as a result of loading: Custom event (ID 223)  
  38.760 Error ClientMultiplayerManager.cpp:1108: mod-LtnManager was registered for the following events when the map was saved but has not re-registered them as a result of loading: Custom event (ID 221)  
  38.760 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "  
mod-LtnManager"  
  38.761 Info ClientMultiplayerManager.cpp:581: UpdateTick(28123446) changing state from(ConnectedLoadingMap) to(Failed)`

**Comment by raiguard** [comment]
Could you send me a save file containing all of your enabled mods so I can test this?

**Comment by aoakeley** [comment]
Here is the save I am trying to add LTN Manager too.  I started a new blank save on the same server with the same mods and did not receive an error on join.

https://www.dropbox.com/s/znjynpwrjhzr2vw/Pepe_COVID_LIVE_HERE.zip?dl=0

**Comment by raiguard** [comment]
Hmm, when I try to replicate it by running two instances of the game on my PC, I can't get it to happen.

Guess it's time to learn how to host a server!

**Comment by aoakeley** [comment]
:)  It's pretty easy but if you have any questions let me know.  You'll have to set the server settings .json  (../config/server-settings.json) and point the exe at the save game ( .\bin\x64\factorio --start-server "./saves/savegame.zip" --server-settings ./data/server-settings.json ) at a minimum to host an existing save game.

The server manager works well: https://github.com/mroote/factorio-server-manager  but the readme *could* explicitly state where to put your steam ID/pwd for the mod's to download and update.

**Comment by aoakeley** [comment]
Well... somehow it's fixed now.  I noticed from the first error log that RecipeBook was generating the same type of error, but only when I enabled LTNManager.  I disabled LTNManager and restarted a few times and then RecipeBook started generating the event manager error.  On a whim I disabled RecipeBook and enabled LTNManager (a combination I had already tried multiple times) and LTNManager now works.  

I'll update this thread if I find any additional information but I had to guess it's a chance thing of events de-syncing during player join first time the mod is used?

Praise Kek a working LTN manager again!!!  Thanks raiguard!

**Comment by raiguard** [comment]
O.o

I actually had this exact same issue with Recipe Book and Quick Item Search (one of my less popular mods), and it was being caused by the Death Markers mod. I never found the actual reason why it was erroring, just that enabling Death Markers made my event manager freak out. Maybe if I can set up my own dedicated server to use for testing I'll be able to pin it down.

**Comment by aoakeley** [comment]
Interesting.  While troubleshooting I deleted some unused (disabled) mods and one of them *was* Death Markers, but as it was disabled I don't know if it's related.  I tried re-enabling Recipe Book and both RB and LTNManager event handler error'ed again.  Removing RB allows LTNM to work as previously.

**Comment by raiguard** [comment]
Does it need to be a Linux installation? I have a VM on my brother's server but it's a Windows VM.

**Comment by raiguard** [comment]
I got it to reproduce by enabling Death Markers... I'm going to investigate and see what I can find. Though this kind of bug is extremely difficult to pin down. _sigh_

**Comment by raiguard** [comment]
WTF... now I can't reproduce it at all. I have Death Markers, Recipe Book, _and_ Quick Item Search enabled, and no dice. I do have a sneaking suspicion as to what could be causing it, though...

It involves a bit of rewriting on my translation module, but it should be doable.

**Comment by raiguard** [comment]
I just pushed an update to RaiLuaLib. Could you please download it and see if the issue has been resolved?

**Comment by raiguard** [comment]
I also released an LTN Manager update as well.

**Comment by aoakeley** [comment]
I get a new error when I include RecipeBook [attempt to index local 'player_data' (a nil value)].  Without RecipeBook seems to be working great.

Client and server logs: [link](https://gist.github.com/aoakeley/5647827013d2ede16b29221ef7e155b1)

**Comment by raiguard** [comment]
Whoops! I'll fix that pronto.

**Comment by raiguard** [comment]
I pushed the update to Recipe Book. Hopefully nothing broke!

**Comment by aoakeley** [comment]
That makes sense and would explain the behavior I observed.  Fancy setup!  Thanks 1000x's for all your hard work!!! 

I'm still getting (I think) the same error I got earlier with RecipeBook updated and enabled:

2020/04/11 22:28:12 Factorio Server:   83.827 Info ServerMultiplayerManager.cpp:923: updateTick(31857759) received stateChanged peerID(1) oldState(TryingToCatchUp) newState(WaitingForCommandToStartSendingTickClosures)
2020/04/11 22:28:12 Factorio Server:   83.827 Info GameActionHandler.cpp:4334: UpdateTick (31857759) processed PlayerJoinGame peerID(1) playerIndex(0) mode(connect)
2020/04/11 22:28:12 Factorio Server:   83.828 Error MainLoop.cpp:1202: Exception at tick 31857759: The mod Recipe Book (1.2.3) caused a non-recoverable error.
2020/04/11 22:28:12 [83.828 Error MainLoop.cpp:1202: Exception at tick 31857759: The mod Recipe Book (1.2.3) caused a non-recoverable error.]
2020/04/11 22:28:12 Factorio Server: Please report this error to the mod author.
2020/04/11 22:28:12 Factorio Server:
2020/04/11 22:28:12 Factorio Server: Error while running event RecipeBook::on_player_joined_game (ID 43)
2020/04/11 22:28:12 Factorio Server: __RaiLuaLib__/lualib/translation.lua:168: attempt to index local 'player_data' (a nil value)
2020/04/11 22:28:12 Factorio Server: stack traceback:
2020/04/11 22:28:12 Factorio Server:    __RaiLuaLib__/lualib/translation.lua:168: in function 'start'
2020/04/11 22:28:12 Factorio Server:    __RecipeBook__/control.lua:103: in function 'run_translations'
2020/04/11 22:28:12 Factorio Server:    __RecipeBook__/control.lua:165: in function 'handler'
2020/04/11 22:28:12 Factorio Server:    __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
2020/04/11 22:28:12 Factorio Server:   83.828 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod Recipe Book (1.2.3) caused a non-recoverable error.
2020/04/11 22:28:12 [83.828 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod Recipe Book (1.2.3) caused a non-recoverable error.]
2020/04/11 22:28:12 Factorio Server: Please report this error to the mod author.
2020/04/11 22:28:12 Factorio Server:
2020/04/11 22:28:12 Factorio Server: Error while running event RecipeBook::on_player_joined_game (ID 43)
2020/04/11 22:28:12 Factorio Server: __RaiLuaLib__/lualib/translation.lua:168: attempt to index local 'player_data' (a nil value)
2020/04/11 22:28:12 Factorio Server: stack traceback:
2020/04/11 22:28:12 Factorio Server:    __RaiLuaLib__/lualib/translation.lua:168: in function 'start'
2020/04/11 22:28:12 Factorio Server:    __RecipeBook__/control.lua:103: in function 'run_translations'
2020/04/11 22:28:12 Factorio Server:    __RecipeBook__/control.lua:165: in function 'handler'
2020/04/11 22:28:12 Factorio Server:    __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>"
2020/04/11 22:28:12 Factorio Server:   83.828 Info ServerMultiplayerManager.cpp:774: updateTick(31857759) changing state from(InGame) to(Failed)
2020/04/11 22:28:12 Factorio Server:   83.829 Quitting: multiplayer error.

**Comment by raiguard** [comment]
What the... I thought I fixed that! How strange.

**Comment by raiguard** [comment]
Oh... frick. I _did_ fix it because it was actually a problem with RaiLuaLib, not Recipe Book. Then I accidentally undid the change somewhere and forgot about it.

Pushing the update soon.

**Comment by raiguard** [comment]
Sorry it took so long, I pushed the LtnManager update as well now. _Hopefully_ everything should be good!

**Comment by aoakeley** [comment]
All is well here with Recipe Book included.  Sorry for the bag of worms and thanks again!

**Comment by raiguard** [comment]
No problem! I'm glad we were able to get it sorted. This issue had been plaguing me for months.

And just in time too, since we just started a global Factorio library project and my translation engine will be a part of it. :D
