### ISSUE TITLE
Incorrect pickup

### ISSUE THREAD

**Issue by jarquafelmu** [raiguard/Factorio-LtnManager#7]
I am not sure what this alert is telling me, its taking things to the correct place

![image](https://user-images.githubusercontent.com/5807272/78951691-3ae22580-7a90-11ea-9baa-6a94bccd00ca.png)

**Comment by raiguard** [comment]
Someone else also reported this, I'm looking into it. For now you can disable the popups in the mod settings. Thank you!

**Comment by raiguard** [comment]
I've released a patch, please try it now!

**Comment by jarquafelmu** [comment]
I am still getting these alerts

![image](https://user-images.githubusercontent.com/5807272/78955518-bb0e8800-7a9c-11ea-9ac2-8361660342bc.png)

**Comment by raiguard** [comment]
Could you please send me your save file? You can PM me on Discord or post a link here.

**Comment by raiguard** [comment]
Alternatively, you could type this command into the console and send me a screenshot of what it does:

`/c __LtnManager__ game.print(serpent.block(global.data.alerts))`

**Comment by jarquafelmu** [comment]
I should have sent this before, I apologize for not doing so
https://drive.google.com/open?id=1jqr1qUfBQkbW_xGrKgo7Uzelu1SZA7sl

**Comment by raiguard** [comment]
It's fine. It's a good idea for the future though, if you're experiencing a bug, to post a link to the save file.

**Comment by jarquafelmu** [comment]
Yeah I do it for all of my reports on the mod portal, it just slipped my mind here

**Comment by raiguard** [comment]
So, the numbers actually are off. The pumps you're using are so fast that they're overfilling the fluid wagons so the numbers don't match. I didn't think of this when I made the alert.

What I'm going to do is if the actually shipped amount is within a reasonable margin of error (say, 1000), I'll let it slide. I'll also make this a configurable option so those like you with an insane amount of mods can make it work.

Thank you for the report!

**Comment by raiguard** [comment]
Well, the same thing happens with items. I'm just naiive and forgot that they'll always try to move a full stack if they can.

I'm just gonna completely disable this alert until I can figure out the best way to handle this.

**Comment by jarquafelmu** [comment]
that sounds like a decent plan and it sounds that you have the right direction

**Comment by raiguard** [comment]
I pushed the patch. I also added amounts to the material button tooltips, for easy reference:

![image](https://user-images.githubusercontent.com/3515394/78958329-fd3bc780-7aa4-11ea-8397-28629b9e64fb.png)

**Comment by jarquafelmu** [comment]
perfect
